Develop
ClevertecFrontendLab/sprint1-flyether pull request #1
Opened 2023-01-25 20:28 UTC by flyether

2023-01-25 20:31 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674678664/content-window.png)

2023-01-25 20:59 UTC, klichkovskiy requested changes
Много критических замечаний. Исправь пожалуйста.

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +  return (
Название картинок лучше с маленькой буквы. Это же не компонент.

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +    <section className={styles.main__page}>
Нет адаптива на 1440px
![image](https://user-images.githubusercontent.com/62481116/214686442-d7f807cb-4aa7-4bda-9400-383b5af1e814.png)
Исправить

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
> +    <section className={styles.main__page}>
![image](https://user-images.githubusercontent.com/62481116/214686586-bc8c4ba0-a790-40c3-a107-880272c99f84.png)
Так тоже не должно быть

2023-01-25 20:59 UTC, klichkovskiy commented on src/components/inputs/search-input.tsx
> +      <input
![image](https://user-images.githubusercontent.com/62481116/214687214-4227cdaa-c57f-47f0-ae68-2ad6f1d714f8.png)
Так не должно быть делай переход на другой вид раньше.

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/214687442-b5b9964d-7ca9-4d19-9353-fb0bd98c9f89.png)
Опять 1440px(

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/214687606-436fbdb9-8676-4f1d-b40b-27bb9620d3f0.png)
А это 768px

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/214687676-04d2736f-5e57-4b82-a2c9-2157bb2d4ef9.png)
320px(

2023-01-25 20:59 UTC, klichkovskiy commented on src/pages/book/book-page.tsx
> +export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/214687795-0872e333-9c8f-43d2-bfcf-57224ee474cc.png)
Еще 320

2023-01-25 20:59 UTC, klichkovskiy commented on src/components/cards-components/books-data.ts
> +export const booksData: Books[] = [
А чего этот файл здесь?

2023-01-25 20:59 UTC, klichkovskiy commented on src/components/cards-components/card-book.tsx
> +
Плохая практика так много пробелов делать

2023-01-25 20:59 UTC, klichkovskiy commented on src/components/cards-components/tile-cards.tsx
> +export const TileCards = ({books}: Props ) => (
Что-то в этой папке куча-мала

2023-01-26 18:19 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674757142/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674757142/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674757142/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-26 18:33 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674757995/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674757995/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674757995/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-01-26 18:44 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674758691/content-window.png)

2023-01-26 19:01 UTC, klichkovskiy requested changes

2023-01-26 19:01 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
>  import { ButtonListTile, ButtonRating } from '../../components/buttons'
И тут 2 компонента. Давай мы их разделим)

2023-01-26 19:01 UTC, klichkovskiy commented on src/pages/main/main-page.tsx
>  import styles from './main-page.module.css'
![image](https://user-images.githubusercontent.com/62481116/214925728-029b271b-be3d-43d3-9acb-2fafdd645368.png)
Сделай циферки как в макете

2023-01-27 09:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674811072/content-window.png)

2023-01-27 09:29 UTC, klichkovskiy requested changes
Доработай ВСЕ ошибки, и перепроверь у себя как оно выглядит.

2023-01-27 09:29 UTC, klichkovskiy commented on src/components/breadcrumbs/breadcrumbs.tsx
> +export function Breadcrumbs({ category, bookId, categoryCyrillic, label }: Props) {
![image](https://user-images.githubusercontent.com/62481116/215052267-234a6115-8d08-4c78-9ca5-646e6be8e576.png)
Опять не по макету
![image](https://user-images.githubusercontent.com/62481116/215052324-d5c546fc-b89f-43ff-b84e-5679f617492a.png)
Вот как в макете

2023-01-27 09:29 UTC, klichkovskiy commented on src/components/breadcrumbs/breadcrumbs.tsx
> +export function Breadcrumbs({ category, bookId, categoryCyrillic, label }: Props) {
Тоже самое 1440
![image](https://user-images.githubusercontent.com/62481116/215052419-0c1bc5fb-3914-456b-9392-972400e229cc.png)
Вот так в макете
![image](https://user-images.githubusercontent.com/62481116/215052504-c663260f-5a5b-4756-af6f-8e8b88014dd4.png)

2023-01-27 09:29 UTC, klichkovskiy commented on src/components/inputs/serch-input/search-input.tsx
>  import styles from './search-inputs.module.css'
![image](https://user-images.githubusercontent.com/62481116/215052638-67243adb-30f9-45af-8dc3-148f3103e94d.png)
По макету там весь текст помещается, сделай ширину инпута больше

2023-01-27 09:29 UTC, klichkovskiy commented on src/components/side-bar/side-bar.module.css
>  .link__number {
![image](https://user-images.githubusercontent.com/62481116/215053111-015e1bdd-2e86-4cd2-8dda-585602aae7f5.png)
Что-то не сработало, перепроверь

2023-01-27 09:47 UTC, flyether commented on src/components/breadcrumbs/breadcrumbs.tsx
> +export function Breadcrumbs({ category, bookId, categoryCyrillic, label }: Props) {
"Вот как в макете" очень извиняюсь но не понимаю про что именно. Если это про текст, то у меня там с примера главной разные книги с разным текстом и в симуляции фетча книги разные приходят. В данные только одну книгу надо? Или это про стили ( шрифт я с фигмы брала)

2023-01-27 09:49 UTC, flyether commented on src/components/breadcrumbs/breadcrumbs.tsx
> +export function Breadcrumbs({ category, bookId, categoryCyrillic, label }: Props) {
или расположение крошек относительно серого контейнера?

2023-01-27 11:42 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/flyether/1674819746/content-window.png)

2023-01-27 11:54 UTC, klichkovskiy approved these changes
Остались мелкие косяки. Если хочешь, можешь исправить к 2 спринту. Я пока делаю апрув)))

2023-01-27 11:55 UTC, klichkovskiy commented on src/components/breadcrumbs/breadcrumbs.tsx
> +export function Breadcrumbs({ category, bookId, categoryCyrillic, label }: Props) {
Расположение крошек

2023-01-27 12:02 UTC, merged